In [71]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor

In [72]:
df = pd.read_csv ("boston_housing.csv", sep = "\s+|\t+|\s+\t+|\t+\s+",  header= None, 
                  names=["crim", "zn", "indus", "chas", "nox", "rm", "age", "dis", "rad", "tax", "ptratio", 
                         "black", "lstat", "medv"], engine='python')

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 506 entries, 1 to 506
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    float64
 10  ptratio  506 non-null    float64
 11  black    506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 59.3 KB

In [74]:
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [75]:
df.tail()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [76]:
df.sample(5,random_state=42)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
174,0.09178,0.0,4.05,0,0.510,6.416,84.1,2.6463,5,296.0,16.6,395.50,9.04,23.6
275,0.05644,40.0,6.41,1,0.447,6.758,32.9,4.0776,4,254.0,17.6,396.90,3.53,32.4
492,0.10574,0.0,27.74,0,0.609,5.983,98.8,1.8681,4,711.0,20.1,390.11,18.07,13.6
73,0.09164,0.0,10.81,0,0.413,6.065,7.8,5.2873,4,305.0,19.2,390.91,5.52,22.8
453,5.09017,0.0,18.10,0,0.713,6.297,91.8,2.3682,24,666.0,20.2,385.09,17.27,16.1

In [77]:
df.drop('medv', axis=1).head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33

In [78]:
df['medv'].head()

1    24.0
2    21.6
3    34.7
4    33.4
5    36.2
Name: medv, dtype: float64

In [79]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('medv',axis=1), 
                                                    df['medv'], 
                                                    test_size=0.3, 
                                                    random_state=777)

In [80]:
print(X_train.shape)
print(X_test.shape)

(354, 13)
(152, 13)

In [81]:
LnR = LinearRegression()

In [82]:
LnR.fit(X_train, y_train)

LinearRegression()

In [83]:
pred = LnR.predict(X_test)

In [84]:
pred_train = LnR.predict(X_train)

In [86]:
#оценка на глаз
test_pred = X_test.copy()
test_pred['predict'] = pred
test_pred['real_medv'] = y_test
test_pred[['predict','real_medv']].head()

       predict  real_medv
208  17.707702       22.5
426  10.399776        8.3
409  13.935423       17.2
64   21.871811       25.0
291  33.531205       28.5

In [87]:
print('Ошибка RMSE =',mean_squared_error(y_test, pred))
print('Ошибка RMSE =',mean_squared_error(y_train, pred_train))

Ошибка RMSE = 25.347913375305524
Ошибка RMSE = 21.024239146904783

In [88]:
RFR = RandomForestRegressor()

In [89]:
RFR.fit(X_train, y_train)

RandomForestRegressor()

In [90]:
pred_RFR = RFR.predict(X_test)
pred_RFR_train = RFR.predict(X_train)

In [91]:
print('Ошибка RMSE =',mean_squared_error(y_test, pred_RFR))
print('Ошибка RMSE =',mean_squared_error(y_train, pred_RFR_train))

Ошибка RMSE = 11.329486078947374
Ошибка RMSE = 1.6202275649717537